### ISSUE TITLE
Build Issue with 'android.injected.build.density' is deprecated for  8.0 Gradle plugin

### ISSUE THREAD

**Issue by slok1368** [m-arquiza/Workoutholic#85]
1.  Steps:
   - When hitting "MakeProject", BUILD SUCCESSFUL
   - Then Run App, I get the following error included at the end of this post
2. Expected to build successful, is there a specific Gradle version I should be using?
   `Build file 'D:\Git Repos\CSE 403 - SDE\WorkoutHolic\Workoutholic\app\build.gradle' line: 2
3. Build bug.
4. Additonal Information:\
In project structure:
- Android Gradle Plugin Version 8.0.0
- Gradle Version 8.0
- Gradle JDK 17 

>An exception occurred applying plugin request [id: 'com.android.application']
> Failed to apply plugin 'com.android.internal.application'.
   > The option 'android.injected.build.density' is deprecated.
     It was removed in version 8.0 of the Android Gradle plugin.
     Density property injection from Android Studio has been removed.

>* Try:
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

>* Exception is:
>org.gradle.api.plugins.InvalidPluginException: An exception occurred applying plugin request [id: 'com.android.application']
	at org.gradle.plugin.use.internal.DefaultPluginRequestApplicator.exceptionOccurred(DefaultPluginRequestApplicator.java:222)
	at org.gradle.plugin.use.internal.DefaultPluginRequestApplicator.applyPlugin(DefaultPluginRequestApplicator.java:204)
	at org.gradle.plugin.use.internal.DefaultPluginRequestApplicator.applyPlugin(DefaultPluginRequestApplicator.java:146)
	at org.gradle.plugin.use.internal.DefaultPluginRequestApplicator.access$200(DefaultPluginRequestApplicator.java:60)
	at org.gradle.plugin.use.internal.DefaultPluginRequestApplicator$1$1.lambda$add$1(DefaultPluginRequestApplicator.java:119)
	at 
	...
`

**Comment by Sonnhid** [comment]
Did you try syncing the gradle.build? You might have to sync multiple times, then you should be able to run the app config
